Improve .travis.yml in branch libvalidsdp
* Rely on the mathcomp/mathcomp Docker images
* Avoid {docker commit, docker rm}
* Use "opam pin add -n -k path libvalidsdp ."
* Replace ValidSDP with CONTRIB_NAME=validsdp

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,56 +9,60 @@ services:
 env:
   global:
   - NJOBS="2"
+  - CONTRIB_NAME="validsdp"
   - COQEAL_URL="https://github.com/CoqEAL/CoqEAL.git"
   - COQEAL_VERSION="d205c98bc36e284759956bee6c8886d548e2e9d0"
   matrix:
-  - COQ_IMAGE="erikmd/coq:8.7.2_mathcomp-1.7.0"
-  - COQ_IMAGE="erikmd/coq:8.8.1_mathcomp-1.7.0"
+  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-8.8"
+  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-8.7"
 
 install: |
-  # Prepare the coq-deps docker image with all dependencies
-  # In case of no-output timeout, prepend "travis_wait" to:
-  docker run --name=COQ ${COQ_IMAGE} /bin/bash --login -c "
+  # Prepare the COQ container
+  docker pull ${COQ_IMAGE}
+  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
+  docker exec COQ /bin/bash --login -c "
     # pass --login so we can use “travis_retry” and omit “opam config exec --”
     # and this bash script is double-quoted to interpolate Travis CI env vars:
     echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
     export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
-    set -e # exit on failure
-    set -x # trace for debug
+    set -ex  # -e = exit on failure; -x = trace for debug
+    : Updating OPAM cache
     opam update -y
+    : Updating APT cache
     exec {fd}>&2 # copy stderr to some unused fd
     travis_retry bash -o pipefail -c \"sudo apt-get update -y -q 2>&1 | tee /dev/fd/\$fd | ( ! grep -q -e '^Err:' -e '^E:' )\"
     exec {fd}>&- # close file descriptor
+    : Installing APT deps
     # “sudo apt-get update -y -q” is mandatory before “opam depext -i”
     travis_retry opam depext -i -y conf-gmp.1 conf-sdpa.1
     sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # optional
-    opam install -y -j ${NJOBS} coq-flocq.3.0.0 coq-interval.3.4.0 osdp camlp4 \
-      coq-mathcomp-multinomials.1.1 coq-paramcoq.1.1.0
-    : Building CoqEAL...
+    : Installing OPAM deps
+    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
+    opam pin add -n -k path coq-libvalidsdp .
+    opam install -y -v -j ${NJOBS} coq-libvalidsdp
+    opam install -y -v -j ${NJOBS} coq-mathcomp-multinomials.1.1 coq-paramcoq.1.1.0 osdp
+    opam config list
+    opam repo list
+    opam list
+    : Building CoqEAL
     git clone -n ${COQEAL_URL} ~coq/coqeal
     cd ~coq/coqeal
     git checkout ${COQEAL_VERSION}
     pushd theory && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd
     pushd refinements && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} && make install && popd
-    echo 'Install done.'"
-  docker commit COQ coq-deps
-  docker rm COQ
+    : done"
 
 script:
-- echo -e "${ANSI_YELLOW}Building ValidSDP...${ANSI_RESET}" && echo -en 'travis_fold:start:validsdp\\r'
+- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
 - |
-  docker run --rm -v ${TRAVIS_BUILD_DIR}:/home/coq/validsdp coq-deps /bin/bash --login -c "
+  # In case of no-output timeout, prepend "travis_wait" to:
+  docker exec COQ /bin/bash --login -c "
     export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
-    set -e # exit on failure
-    set -x # trace for debug
-    sudo chown -R coq:coq ~coq/validsdp
-    cd ~coq/validsdp
-    cd libvalidsdp
+    set -ex
+    cd /home/coq/${CONTRIB_NAME}
     ./autogen.sh
     ./configure
     make install
-    cd ..
-    ./autogen.sh
-    ./configure
-    make install"
-- echo -en 'travis_fold:end:validsdp\\r'
+    : done"
+- docker stop COQ  # optional
+- echo -en 'travis_fold:end:script\\r'
